### ISSUE TITLE
Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by gaearon** [pmmmwh/react-refresh-webpack-plugin#6] opened 2019-12-06 20:20 UTC
After adding this plugin to an ejected CRA project I get:

```
Cannot read property 'mode' of undefined
```

Are we assuming some particular webpack version?

**Comment by drather19** [comment] 2019-12-06 21:08
That's odd... I also tried it on a brand new CRA project using the instructions in the README, but didn't encounter the same error. I did the following:

```
npx create-react-app . --typescript
npm run eject
npm install react-refresh-webpack-plugin react-refresh
```

**Comment by gaearon** [comment] 2019-12-06 22:15
I tried this on ejected “todomvc” app from Redux repo examples folder.

**Comment by pmmmwh** [comment] 2019-12-07 09:07
> After adding this plugin to an ejected CRA project I get:
> 
> ```
> Cannot read property 'mode' of undefined
> ```
> 
> Are we assuming some particular webpack version?

That's my bad - I did some sniffing on webpack mode but did not add a check for its existence.

**Comment by gaearon** [comment] 2019-12-08 13:17
> I did some sniffing on webpack mode but did not add a check for its existence.

Maybe you’re checking it incorrectly? It sounds weird you’d have to sniff for it.

What does TerserPlugin do to only turn on in production mode? We need to do the opposite of that.

**Comment by pmmmwh** [comment] 2019-12-08 13:19
> > I did some sniffing on webpack mode but did not add a check for its existence.
> 
> Maybe you’re checking it incorrectly? It sounds weird you’d have to sniff for it.
> 
> What does TerserPlugin do to only turn on in production mode? We need to do the opposite of that.

I worded it inappropriately. I edited my comment above to reflect what is actually happening.

I'll check how TerserPlugin does it.

**Comment by MasterCassim** [comment] 2019-12-08 13:45
Webpack automatically adds the TerserPlugin for production builds since v4:

> Sets process.env.NODE_ENV on DefinePlugin to value production . Enables FlagDependencyUsagePlugin , FlagIncludedChunksPlugin , ModuleConcatenationPlugin , NoEmitOnErrorsPlugin , OccurrenceOrderPlugin , SideEffectsFlagPlugin and TerserPlugin .

-> https://webpack.js.org/configuration/mode/

**Comment by pmmmwh** [comment] 2019-12-08 13:55
> I tried this on ejected “todomvc” app from Redux repo examples folder.

@gaearon I couldn't reproduce this. I just cloned the Redux repo and ejected the same app (`todomvc`), adding in only the babel plugin and the webpack plugin and I didn't hit this issue. (I hit the issue with #8 / #11 , but they are unrelated to mode checking)

**Comment by luisgrases** [comment] 2019-12-14 00:04
I believe it requires webpack 5

**Comment by pmmmwh** [comment] 2019-12-16 15:21
> I believe it requires webpack 5

Can you explain a bit more? You mean the error only triggers in Webpack 5 or the repo only works in Webpack 5?

**Comment by luisgrases** [comment] 2019-12-16 17:26
I believe the repo only works in webpack 5

**Comment by pmmmwh** [comment] 2019-12-17 14:42
> I believe the repo only works in webpack 5

No, the repo does not work with Webpack 5. All testing I've done and all examples provided here all uses Webpack 4.41.2. So if the plugin does not work for you on webpack 4, please file an issue and provide a reproduce-able case.

**Comment by pmmmwh** [comment] 2020-04-07 21:13
I don't think this is still valid (and I am unable to reproduce it), so I'll close this for now.

**Closed by pmmmwh** 2020-04-07 21:13 UTC

**Comment by paaacman** [comment] 2020-08-26 16:48
I reproduced this by adding the Webpack conf, in `webpack.config`, in `resolve.plugins` section, not in `plugins` section
```
resolve: {
  plugins: [
    new ReactRefreshWebpackPlugin(),
  ],
}
```

**Comment by pmmmwh** [comment] 2020-08-27 06:57
> I reproduced this by adding the Webpack conf, in `webpack.config`, in `resolve.plugins` section, not in `plugins` section
> 
> ```
> resolve: {
>   plugins: [
>     new ReactRefreshWebpackPlugin(),
>   ],
> }
> ```
> 
> It's working by putting the configuration in webpack plugins section.

Well I don't think this is something that we have to deal with ... ? All plugins could fail if you use them as resolver plugins?

**Comment by paaacman** [comment] 2020-08-27 07:03
> Well I don't think this is something that we have to deal with ... ? All plugins could fail if you use them as resolver plugins?

I totally agree with you, you should not handle this case, it's a configuration error made by us.
I added this comment to help anybody who, like me, made this mistake and look for a solution here :)

**Comment by denissabramovs** [comment] 2023-04-17 12:56
Same here, i guess that is something related to versions inconsistencies.

**Comment by denissabramovs** [comment] 2023-04-17 13:24
Here what is forwarded into apply method:
```
  apply(compiler) {
    console.log(util.inspect(compiler, false, null))
    process.exit()
```

https://gist.github.com/denissabramovs/6946875e786ea37c096928e77ff51f8a

It doesn't have mode, logger and others properties.
