### ISSUE TITLE
SyntaxError: Unexpected token '_', "__webpack_"... is not valid JSON

### ISSUE THREAD

**Issue by whitetrefoil** [pmmmwh/react-refresh-webpack-plugin#749] opened 2023-04-25 09:00 UTC
This plugin: v0.5.10
Webpack: v5.80.0
After 1st file change:
```
SyntaxError: Unexpected token '_', "__webpack_"... is not valid JSON
    at JSON.parse (<anonymous>)
    at <rootdir>/node_modules/ts-loader/dist/watch-run.js:82:39
    at <rootdir>/node_modules/webpack/lib/dependencies/LoaderPlugin.js:152:16
    at <rootdir>/node_modules/webpack/lib/Compilation.js:1935:5
    at <rootdir>/node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (<rootdir>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._handleResult (<rootdir>/node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at <rootdir>/node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at <rootdir>/node_modules/webpack/lib/Compilation.js:1396:15
    at <rootdir>/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (<rootdir>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (<rootdir>/node_modules/webpack/lib/Cache.js:107:20)
    at CacheFacade.store (<rootdir>/node_modules/webpack/lib/CacheFacade.js:283:15)
    at <rootdir>/node_modules/webpack/lib/Compilation.js:1387:26
    at <rootdir>/node_modules/webpack/lib/NormalModule.js:1064:14
    at jobDone (<rootdir>/node_modules/webpack/lib/FileSystemInfo.js:1995:5)
    at FileSystemInfo.createSnapshot (<rootdir>/node_modules/webpack/lib/FileSystemInfo.js:2330:3)
    at handleBuildDone (<rootdir>/node_modules/webpack/lib/NormalModule.js:1049:32)
    at handleParseResult (<rootdir>/node_modules/webpack/lib/NormalModule.js:994:12)
    at <rootdir>/node_modules/webpack/lib/NormalModule.js:1101:4
    at processResult (<rootdir>/node_modules/webpack/lib/NormalModule.js:803:11)
    at <rootdir>/node_modules/webpack/lib/NormalModule.js:863:5
    at <rootdir>/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (<rootdir>/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (<rootdir>/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at <rootdir>/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (<rootdir>/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at <rootdir>/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:94:7
```

Did a debug at `watch-run.js:82`, the `source` is:
```js
__webpack_require__.$Refresh$.runtime = require('<rootdir>/node_modules/react-refresh/runtime.js');

"import ... <my source codes here>"

var $ReactRefreshModuleId$ = __webpack_require__.$Refresh$.moduleId;
var $ReactRefreshCurrentExports$ = __react_refresh_utils__.getModuleExports(
	$ReactRefreshModuleId$
);

function $ReactRefreshModuleRuntime$(exports) {
	if (module.hot) {
		var errorOverlay;
		if (typeof __react_refresh_error_overlay__ !== 'undefined') {
			errorOverlay = __react_refresh_error_overlay__;
		}
		var testMode;
		if (typeof __react_refresh_test__ !== 'undefined') {
			testMode = __react_refresh_test__;
		}
		return __react_refresh_utils__.executeRuntime(
			exports,
			$ReactRefreshModuleId$,
			module.hot,
			errorOverlay,
			testMode
		);
	}
}

if (typeof Promise !== 'undefined' && $ReactRefreshCurrentExports$ instanceof Promise) {
	$ReactRefreshCurrentExports$.then($ReactRefreshModuleRuntime$);
} else {
	$ReactRefreshModuleRuntime$($ReactRefreshCurrentExports$);
}
```

It seems the `source` is a JSON string, and this plugin places its code outside of the quotes...

**Comment by pmmmwh** [comment] 2023-08-09 14:48
Duplicate of #750 - this is technically an issue from `ts-loader`, will see what we can do ...

**Closed** 2023-08-11 01:59 UTC
