### ISSUE TITLE
Plugin don't work if react root component defined in index.js file

### ISSUE THREAD

**Issue by farwayer** [pmmmwh/react-refresh-webpack-plugin#347] opened 2021-04-08 03:54 UTC
Reproduce demo for this and #346
https://github.com/farwayer/rrwp-issues

**Comment by gaearon** [comment] 2021-04-08 12:35
That's expected, it works for components defined in their own files.

**Comment by pmmmwh** [comment] 2021-04-24 23:09
Closing as this is the expected behaviour -
RR relies on bubbling and marking exports as safe to re-execute.
Since the component is defined at root, there's no way for us to check for exports nor there exist any route we can bubble.

**Closed by pmmmwh** 2021-04-24 23:09 UTC
