### ISSUE TITLE
Using extended classes for props doesn't get picked up by react-refresh

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pmmmwh/react-refresh-webpack-plugin#258] opened 2020-11-18 11:57 UTC
I have a curious case where I am using classes instead of plain old JS objects as input properties for my components. 

Simple usage with classes like the following works as expected and maintains its state when I make changes to styling etc.
```js
import { createElement, useState } from 'react' 
 
export class CounterProps {
    constructor(title) {
        this.title = title;
    }
}

export const Counter = (props) => {
  const [count, setCount] = useState(0)
  return createElement("div", null, 
    createElement("h1", null, props.title),
    createElement("h1", null, count), 
    createElement("button", { onClick: () => setCount(count + 1) }, "Increment")
  );
}

export const Counters = () => {
  return createElement("div", null, 
     createElement(Counter, new CounterProps("Page title")),
     createElement(Counter, new CounterProps("Another title"))
   );
}
```
However, once I extend `CounterProps` with *anything* then fast-refresh doesn't pick up the changes anymore:
```js
export class Anything { }

export class CounterProps extends Anything {
    constructor(title) {
        super();
        this.title = title;
    }
}
```

I am using the following versions (on Windows):
 - react-refresh v0.9.0
 - @pmmmwh/react-refresh-webpack-plugin v0.4.3
 - react v16.14.0
 - webpack v4.44.2

**Comment by Zaid-Ajaj** [comment] 2020-11-21 02:54
I just confirmed that removing `export` from the class definitions makes react-refresh work again! Also if these types were defined in another file and exported, then it all works out.  Maybe React-refresh is detecting classes as function components because they are upper-cased?

**Comment by gaearon** [comment] 2020-11-21 14:37
I would expect that classes without a render method shouldn’t be detected as components. But you should verify in react-refresh/runtime source. We could fix it there if that’s the issue.

**Comment by Zaid-Ajaj** [comment] 2020-11-21 16:16
Thanks @gaearon for the quick response! I will have a look at the source code, it is in the main react repo if I remember correctly.

Fixing this would make a huge difference for Fable/React applications!

**Comment by Zaid-Ajaj** [comment] 2020-11-21 17:07
I found [this function](https://github.com/facebook/react/blob/master/packages/react-refresh/src/ReactFreshRuntime.js#L146-L148) called `isReactClass`:
```js
function isReactClass(type) {
  return type.prototype && type.prototype.isReactComponent;
}
```
And tested it locally in the application itself, it correctly returns `undefined` for the class definitions I have above. It doesn't seem to be the cause of the error. I can confirm that the functions returns `true` when the class actually extends `Component` from `react`

**Comment by Zaid-Ajaj** [comment] 2020-11-21 19:41
@gaearon I think the function [`isLikelyComponentType`](https://github.com/facebook/react/blob/master/packages/react-refresh/src/ReactFreshRuntime.js#L671-L720) might be the culprit. Because it returns `true` for an empty class like this:
```js
export const Anything { }

isLikelyComponentType(Anything) // true
```
The fix is to change this part:
```js
if (ownNames.length > 1 || ownNames[0] !== 'constructor') {
  // This looks like a class.
  return true;
}
```
Into 
```js
if (ownNames.length > 1 || ownNames[0] !== 'constructor') {
  // This looks like a class.
  // check whether the class has a render function
  const hasRenderFunction = ownNames.includes("render");
  return hasRenderFunction;
}
```
However, I couldn't verify that this fix actually solves the problem at hand :/ any pointers? Thanks in advance 🙇

**Comment by pmmmwh** [comment] 2020-11-23 23:37
I did some tests, and this is a bit tricky.

After transpilation, empty classes are de-sugared into this:

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Anything = function Anything() {
  _classCallCheck(this, Anything);
};
```

So, with respect to the current heuristic:

https://github.com/facebook/react/blob/e6a0f276307fcb2f1c5bc41d630c5e4c9e95a037/packages/react-refresh/src/ReactFreshRuntime.js#L674-L697

- It will fail the first condition (`type.prototype.isReactComponent` does not exist)
- It will fail the second condition (`ownNames.length` is `0` when de-sugared, `1` when kept intact, `ownNames[0]` is `'constructor'` when not de-sugared)
- It will fail the third condition (`type.prototype.__proto__ === Object.prototype` since it is an empty class/function)

The main question here is whether there exist a heuristic to differentiate empty classes from functions (especially considering when de-sugared to ES5), not the other way around (detecting a render function exists within a class).

**Comment by Zaid-Ajaj** [comment] 2020-11-26 16:15
@pmmmwh Is there anything I can help with in order to fix this issue? Any pointer would be great! 🙏

**Comment by pmmmwh** [comment] 2020-11-26 17:39
> @pmmmwh Is there anything I can help with in order to fix this issue? Any pointer would be great! 🙏

I am actually unsure if this can be solved when a de-sugared empty class is essentially the same as a plain function ... ?

**Comment by Zaid-Ajaj** [comment] 2020-11-26 17:53
Could a babel-macro be implemented to rewrite the definition into something that *can* be detected by react-refresh? 

I mean in my case is really that `Anything` is defined in another module and `CounterProps` extending it makes application fully refresh on changes, instead of the partial refresh.

Maybe there is a simpler way: I checked that making the classes as lower-case still causes the problem, maybe should react-refresh ignore these functions when they are lower-cased?

**Comment by pmmmwh** [comment] 2020-11-30 00:22
> Could a babel-macro be implemented to rewrite the definition into something that _can_ be detected by react-refresh?

What do you have in mind?

> Maybe there is a simpler way: I checked that making the classes as lower-case still causes the problem, maybe should react-refresh ignore these functions when they are lower-cased?

Can you create a reproducible case? I don't seem to be able to see this behaviour in a bare-bones setup.

A Sandbox to demonstrate this:

https://codesandbox.io/s/extend-class-react-refresh-23d00

**Comment by Zaid-Ajaj** [comment] 2020-11-30 00:39
Thanks a lot for the sandbox example, I will try to replicate the configuration as close as possible to this working example and let you know of my findings!

**Comment by Zaid-Ajaj** [comment] 2020-11-30 01:59
@pmmmwh I was able to make the smallest possible repo, it is in [this repository](https://github.com/Zaid-Ajaj/WebpackRefreshRepro) Please have a look at it 🙏 

Run the sample cloning locally and executing
```
npm install
npm run dev
```
Navigate to `localhost:8080` 

Click around to change the state of the counters

Then update the content of the button from "Increment" to "Increment by 1" (inside `Components.fs.js`) and notice react-refresh performing a full page refresh. However, once you change this part
```js
export class CounterProps extends Record {
    constructor(initialCount) {
        super();
        this.initialCount = (initialCount | 0);
    }
}
```
into
```js
export class CounterProps {
    constructor(initialCount) {
        this.initialCount = (initialCount | 0);
    }
}
```
Then react-refresh works as expected and the state is preserved across re-renders

**Comment by pmmmwh** [comment] 2020-11-30 21:35
Thanks for the reproduction - will investigate sometime this week (working on a new release at the moment, see if we can get this fixed in time ...)

**Comment by Zaid-Ajaj** [comment] 2020-11-30 21:40
That would super awesome! @pmmmwh 🙏 Please let me know if I can help with anything

**Comment by pmmmwh** [comment] 2020-12-06 16:29
After a bit of fiddling around I am quite certain that the working case without the super class is actually a false positive that we probably cannot solve - i.e. **IT SHOULD NOT HAVE WORKED**.

The reason -

`Components.fs.js` exports both React components and non-React stuff (classes which act as props) - we shouldn't have constructed a boundary there. The reason why if actually allowed the refresh is because we failed to distinguish that the `CounterProps` class is actually a class, not a function - which in itself is already difficult enough in a native ES6 environment (relying on `toString` checks`), and after Babel this is no way to check it (see babel/babel#5640). However when you add a super class - now we can pick it up and distinguish that, so it will fail properly.

However - if you move `App` into its own file and leave everything behind - the integration would work because we can actually construct a boundary in root level. In general this is the advice I would give out to people - move your "Root" component into a single, self-contained file to ensure that there is always a boundary near root so we don't frequently bail out and force a refresh.

**Comment by Zaid-Ajaj** [comment] 2020-12-15 02:36
Hi @pmmmwh, first of all, thanks a lot for the detailed answer. I now understand why the refresh fails. However, from the perspective of the F# side of things (because I am really talking about JS which is transpiled from F#), it could be possible to add *metadata* to the class declaration which could very well easily allow fast-refresh to pick it up. Two questions arise:
 - Which metadata do you need? It could be a dummy, compiler-generated function with a special name like `$IamClass` which can is returned in the property names array when you ask `Object.getOwnPropertyNames(Test.prototype) => ["constructor", "$IamClass"]` 

 - How to generically tell or hint the plugin that with that information? An option passed to the plugin would do the trick `{ classDetectionHints: ["$IamClass"] }` or something similar. 

What do you think?

**Comment by gaearon** [comment] 2020-12-15 02:57
Oh wait... I completely missed the part about *custom prop classes*.

This is not supported. I don't know why you're doing this but I strongly discourage you from this pattern. It is not idiomatic and will likely lead to other issues.

**Comment by gaearon** [comment] 2020-12-15 02:58
Although I guess you still have the underlying issue which could've been about some other class usage. Just that this one is weird.

**Comment by Zaid-Ajaj** [comment] 2020-12-15 03:21
> I don't know why you're doing this

@gaearon  The reason is simple: this is how F# records are compiled to JavaScript using [Fable](https://fable.io) and these F# records happen to be a really nice way to define lightweight React component prop types:
```fs
type NavigationItemProps = {
    title: string
    active : bool
}

// Component defition
[<ReactComponent>]
let NavigationItem (props: NavigationItemProps) = 
  let (hovered, setHovered) = React.useState(props.active)
  Html.h1 props.title

// call-site: 
NavigationItem { title = "Home"; active = false }
```
There are workarounds of course but I would really appreciate it if we could define React components in F# the following structure: F# source file is called {ComponentName}.fs and contains the props type definition along with the function itself. Potentially having multiple small components and their prop types in the same file when you have small components.

**Comment by pmmmwh** [comment] 2021-02-28 21:35
Sorry for the late reply, totally missed this!

> Which metadata do you need? It could be a dummy, compiler-generated function with a special name like $IamClass which will be returned in the property names array when you ask Object.getOwnPropertyNames(Test.prototype) => ["constructor", "$IamClass"]

Yes, as long as you add some properties/methods it will be different from a plain function so the checks will work.

> How to generically tell or hint the plugin that with that information? An option passed to the plugin would do the trick { classDetectionHints: ["$IamClass"] } or something similar.

I would rather not have this API but rely on actual semantics of classes. I would argue that this is very much an edge case that is only valid in very few cases.

**Comment by pmmmwh** [comment] 2021-06-15 00:41
Going to close this - The plugin is working as intended and this is due to an unfortunate limitation of not having a way to reliably detect classes (before/after transpilation) within the `react-refresh/runtime`.

A simple workaround (since this is mostly related to a `compiler`) is to generate classes that have something more than just the `constructor` itself, like by adding empty class fields as "hints".

**Closed by pmmmwh** 2021-06-15 00:41 UTC

**Comment by forki** [comment] 2022-02-24 10:51
Hey, @Zaid-Ajaj 

I came here from a compiler warning.

![image](https://user-images.githubusercontent.com/57396/155510420-32fd8518-9f37-46d0-8b1d-1ba9bc557ec3.png)

So apparently the issue is closed. Does this mean the warning is obsolete?
