### ISSUE TITLE
Change of not directly exported value does't refresh

### ISSUE THREAD

**Issue by mariusrak** [pmmmwh/react-refresh-webpack-plugin#228] opened 2020-10-19 16:10 UTC
In an imported file I have something like this:

```javascript
const SomeComponent = () => <>Component</>;
SomeComponent.someProperty = something;

export default SomeComponent;
```

when I change the `someProperty` only the imported file is updated but not module that uses the `someProperty`

when I add

```javascript
export const someProperty = SomeComponent.someProperty;
```
it works correctly, i.e. the change in `something` is accepted through a tree and updated.

**Comment by pmmmwh** [comment] 2020-10-25 18:09
Hi - that is in fact a mutation to the exports and I don't think at the moment would be correctly picked up. We currently only diff the export itself - and when you do `obj.a = 'a'` it mutates the object in place. I'm not sure if we want to fix that - partially because looping through all the keys and do a deep object equality might be potentially expensive.

@gaearon what do you think? This pattern I think is quite common in design systems (`List.Item` and alike) and maybe also common for people who uses `PropTypes`.

**Comment by mariusrak** [comment] 2020-10-26 13:58
Would not it be possible to check on components that are using export and check whether they are using some property of it, if yes, then check on update of the property. So it wouldn't be needed to diff whole exports.

**Comment by gaearon** [comment] 2020-10-26 20:18
This is an expected tradeoff. I’ve decided not to support this because it adds a lot more false positives (often nothing “really” changes but there is no way to tell).

Generally we recommend not using this pattern anyway. It is preferred to use ES exports to export multiple components instead of adding them to each other as properties. Similarly, static methods may be considered an anti-pattern because they make it difficult to introduce components in the middle (e.g. wrapping with a HOC can break a static method).

So our recommendation is just to use regular named exports in the first place, and then you don’t have this issue.

**Comment by pmmmwh** [comment] 2020-11-25 01:01
Expected behaviour, won't fix.

**Closed by pmmmwh** 2020-11-25 01:01 UTC
