### ISSUE TITLE
module.hot.accept is not firing

### ISSUE THREAD

**Issue by shannonhochkins** [pmmmwh/react-refresh-webpack-plugin#517] opened 2021-10-06 21:21 UTC
I have implemented based on the recomended settings with babel, here's my config:
```
module.exports = api => {
  // This caches the Babel config
  api.cache.using(() => process.env.NODE_ENV);
  return {
    plugins: [
      // Applies the react-refresh Babel plugin on development mode only
      api.env('development') && 'react-refresh/babel',
      '@babel/plugin-proposal-optional-chaining',
      '@babel/plugin-transform-runtime',
      '@babel/plugin-transform-react-constant-elements',
      '@babel/plugin-transform-react-inline-elements',
      [
        '@emotion',
        {
          // sourceMap is on by default but source maps are dead code eliminated in production
          sourceMap: true,
          autoLabel: 'dev-only',
          labelFormat: '[local]',
          cssPropOptimization: false,
        },
      ],
    ].filter(Boolean),
    presets: [
      [
        '@babel/preset-env',
        {
          debug: false,
          targets: {
            browsers: ['last 2 chrome versions'],
          },
          corejs: '3.6.5',
          useBuiltIns: 'entry',
        },
      ],
      '@babel/preset-typescript',
      [
        '@babel/preset-react',
        { development: !api.env('production'), runtime: 'automatic' },
      ],
    ],
  };
};
```

Previously when using `react-hot-loader` it would hit the accept callback on files you're listening on, ie:

```
module.hot.accept('./someFile', () => {
    console.log('I would see this console log');
});
```

I have the above on in the entry file for a react application

However after adding this plugin and `react-refresh` it doesn't work anymore, any idea why?

**Comment by pmmmwh** [comment] 2021-10-09 18:01
Hi, this is probably intentional behaviour - React Refresh works by setting boundaries on each file, so essentially each file now has a `module.hot.accept()` call in it already. I am not super certain how Webpack handles double calls but that's probably why.

**Comment by pmmmwh** [comment] 2021-11-08 18:07
Closing as expected behaviour and probably wont-fix due to how HMR is implemented.

**Closed by pmmmwh** 2021-11-08 18:07 UTC
