### ISSUE TITLE
Apply plugin to some chunks only

### ISSUE THREAD

**Issue by ghost** [pmmmwh/react-refresh-webpack-plugin#143] opened 2020-07-15 09:28 UTC
Hello, I would like to know whether it's possible to apply the plugin to some chunks only?
I am building the application itself and a couple of WebWorkers within the single webpack build.
As a result, the plugin is applied to the WebWorker code is well.
Due to the `window` usage, it triggers an error.
`ReferenceError: window is not defined`.
I haven't found any options in the documentation that can solve the problem.

**Comment by pmmmwh** [comment] 2020-07-15 14:15
> Hello, I would like to know whether it's possible to apply the plugin to some chunks only?

By specific chunks do you mean entries? We have no control over chunking.

Can you attach the error here too? Is it from the overlay entry?

Currently injected entries does not respect the include/exclude options. If an option to exclude specific entries from the injection, that should solve your problem?

**Comment by DanAtSpark** [comment] 2020-07-16 09:10
@pmmmwh Yes, I mean entries, you are totally correct.
This is the only error I get, I can attach the stack, but it points to access location field of the window object. The code is definitely inserted by the plugin.
Excluding the entry should solve the problem.

**Comment by Saulis** [comment] 2020-08-27 11:34
@pmmmwh I think I have a related issue: I'm having a project with two entries without chunk splitting. Let's call them A and B. This results in `react-refresh` being bundled in both entry points separately, so will have separate runtimes for A and B. Both entries have their clients calls `require('react-refresh/runtime')` and only first (A) of them will be attached the global hooks as intended.

However, now that B receives changes and tries to do a hot update, it doesn't apply them because the [`mountedRoots`](https://github.com/facebook/react/blob/master/packages/react-refresh/src/ReactFreshRuntime.js#L267) is always empty. This is because all the mount callback go to runtime A.

I don't think this is an issue for a chunked project, but for me, it would be nice to be able to disable entry A from the injection.

**Comment by pmmmwh** [comment] 2020-08-27 12:38
> I don't think this is an issue for a chunked project, but for me, it would be nice to be able to disable entry A from the injection.

Please take a look at [this guide](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/docs/rewrite/docs/TROUBLESHOOTING.md#component-not-updating-with-bundle-splitting-techniques).

Selective entry injection is on my radar but won't land soon because my priority right now is on React 17 testing (Sorry!).

**Comment by Saulis** [comment] 2020-08-27 14:30
Thanks for the quick response!

Essentially I have this:
```
entry: {
    index: './app/scripts/client/index',
    styles: './app/scripts/client/styles'
}
```
where `index` is the main entry and `styles` is a really small bundle with just some stylesheets I don't even need hot reloading for. Both of them are loaded on `index.html`. 

So the plugin prepends the react refresh entry for both of them which in turn makes `webpack` bundle `react-refresh` and `react-refresh-webpack-plugin` into both `index` and `styles`. Now, when `index.html` loads `index` and `styles`, and `react-refresh/runtime` is imported twice.

**Comment by pmmmwh** [comment] 2021-07-11 23:54
Closing as it is irrelevant now. The best solution is to use `runtimeChunk: 'single'`.
Refer to the TROUBLESHOOTING docs for more details.

**Closed by pmmmwh** 2021-07-11 23:54 UTC
