### ISSUE TITLE
$RefreshReg$ is not defined

### ISSUE THREAD

**Issue by gkothe** [pmmmwh/react-refresh-webpack-plugin#218] opened 2020-10-01 13:18 UTC
Hello all,
Not sure if this is the right place to post it, but here it goes:

Short Story Mode.
I want to make this template work with react-refresh.
Template:https://github.com/gkothe/site_react_ssr_fast_refresh   (stripped down version of the project that im working)
Error:$RefreshReg$ is not defined

Long Story Mode:
Im somewhat new to webpack/babel e etc. I needed a universal app, (some pages need to be server rendered), so I found a boilerplate some time ago and start coding on it. And its working ok in dev mode (havent got to the production part yet). 
Now I want to use react-refresh to speed up production. I spent more then 4h trying to make my project work with it and no success, i tried looking at the examples, but did no good so this is my last shot. 

Template:https://github.com/gkothe/site_react_ssr_fast_refresh   (stripped down version of the project that im working)
Error:$RefreshReg$ is not defined

There may be something on the configuration of the project that are wrong/useless or whatever ( since it was a boilerplate), but i lack the experience to know it (Any insights on that would be appreciate as well)

Any help would be very much appreciated. 
Thanks

**Comment by gkothe** [comment] 2020-10-09 12:53
I did create a entry.js point that does  
```
 $RefreshReg$ = () => { 
        console.log("yey2");
    };
    $RefreshSig$ = () => type => type;
```

when i make changes in the code it builds those files 
![image](https://user-images.githubusercontent.com/11322245/95585159-3a155680-0a15-11eb-8fe7-c36b1843f7e3.png)
but it never actually reloads on the browser

**Comment by pmmmwh** [comment] 2020-10-18 14:13
Hi, I see that you're running with `webpack --watch` instead of any hot module replacement runtimes. That won't work because by HMR requires separate configuration that is not applied in `watch` modes. I would suggest you trying to run with `webpack-dev-server` instead as a first step.

Also, since you're server side rendering, you most likely would also need to have the plugin (and babel) setup for server side.

**Comment by IlanBeloglovsky** [comment] 2020-12-30 14:29
I'm facing similar issue
I have a react app with typescript that used react-hot-reload that i decided to migrate to react-fast-refresh
i use `webacp-dev-server` with `--hot` flag but i get the same error

**Comment by pmmmwh** [comment] 2020-12-30 22:14
Hi, is it possible to provide a reproduction?

**Comment by sibelius** [comment] 2021-01-08 15:08
@gkothe can you share your entry.js with $RefreshReg$ ?

**Comment by gkothe** [comment] 2021-01-11 12:54
> @gkothe can you share your entry.js with $RefreshReg$ ?

I ended up not using react refresh, so all the modifications were erased

**Comment by pmmmwh** [comment] 2021-01-21 11:52
Hi, can I close this issue? It seems that it is abandoned - I would rather have new issues if someone needs more help on using React Refresh with Webpack universal SSR.

**Comment by gkothe** [comment] 2021-01-21 11:56
> Hi, can I close this issue? It seems that it is abandoned - I would rather have new issues if someone needs more help on using React Refresh with Webpack universal SSR.

yes

**Closed** 2021-01-21 11:59 UTC
