### ISSUE TITLE
Support `type-fest` v4

### ISSUE THREAD

**Issue by ximex** [pmmmwh/react-refresh-webpack-plugin#763] opened 2023-07-17 08:20 UTC
Got this error if i use `type-fest` v4
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @pmmmwh/react-refresh-webpack-plugin@0.5.10
npm ERR! Found: type-fest@4.0.0
npm ERR! node_modules/type-fest
npm ERR!   dev type-fest@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional type-fest@">=0.17.0 <4.0.0" from @pmmmwh/react-refresh-webpack-plugin@0.5.10
npm ERR! node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!   dev @pmmmwh/react-refresh-webpack-plugin@"^0.5.10" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: type-fest@3.13.1
npm ERR! node_modules/type-fest
npm ERR!   peerOptional type-fest@">=0.17.0 <4.0.0" from @pmmmwh/react-refresh-webpack-plugin@0.5.10
npm ERR!   node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!     dev @pmmmwh/react-refresh-webpack-plugin@"^0.5.10" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

it's from the `peerDependencies` `"type-fest": ">=0.17.0 <4.0.0",`

**Comment by tianyingchun** [comment] 2023-08-02 08:21
please update "type-fest". peerDependencies +1

**Comment by pmmmwh** [comment] 2023-08-09 14:35
> @pmmmwh Imho, something, that does not have a footprint in the runtime, should not be a peer dependency. Dev dependency for a type declaration is more than enough.
Correct me if i'm wrong, but there is no objective point in making it runtime dependency, and even if there is any, it can probably be fullfilled with wildcard peer dependency without the hassle of constant version bumps when new version of type-fest is released.

It is marked as an optional peer dependency - if you write a `webpack.config.ts` you do need it to compile your project. The reason we keep the version locked reasonably is because we have had type-level breakages before and we want to control that aspect.

**Comment by ankhzet** [comment] 2023-08-10 08:37
No, it seems, optional peer dependencies do not work as you think they do. Not only "peerDependencies" are treated differently by different package managers (strict peer dependencies are "on" by default in pnpm >=7.0, for example), some tools may use specific configurations, that prevent dependencies bloat and conflicts (i.e. "stricPeerDependecies" in rushjs).

> if you write a webpack.config.ts you do need it to compile your project
No, i don't. Correct me on why and how exactly, if i'm wrong, but as far as i understand, unless i directly consume the [react-refresh-webpack-plugin] sources itself in some way, i don't have to pin my dependencies to those, that this plugin uses internally, unless thy have runtime footprint.
Constraining `library` consumers (99% of users of the library) to the restrictions of `library code` (maybe 1% of users of the library) seems unnecessary. Again, i might missunderstand something, but i'm failing to see what exactly i missunderstood.

I would be gratefull, if you can point me at the exact issue or pr or conversation within this (or any other) repository regarding this topic.

**Comment by pmmmwh** [comment] 2023-08-11 03:54
> No, it seems, optional peer dependencies do not work as you think they do. Not only "peerDependencies" are treated differently by different package managers (strict peer dependencies are "on" by default in pnpm >=7.0, for example), some tools may use specific configurations, that prevent dependencies bloat and conflicts (i.e. "stricPeerDependecies" in rushjs).

I think this is working as intended - optional means if you do not install the package it's fine, but if you install it has to be confined within the supported version space. We will bump the version soon (likely this weekend).

> No, i don't. Correct me on why and how exactly, if i'm wrong, but as far as i understand, unless i directly consume the [react-refresh-webpack-plugin] sources itself in some way, i don't have to pin my dependencies to those, that this plugin uses internally, unless thy have runtime footprint.
Constraining library consumers (99% of users of the library) to the restrictions of library code (maybe 1% of users of the library) seems unnecessary. Again, i might missunderstand something, but i'm failing to see what exactly i missunderstood.
>
> I would be gratefull, if you can point me at the exact issue or pr or conversation within this (or any other) repository regarding this topic.

If you write the following `webpack.config.ts` (note - this has to be a TypeScript file), and `type-fest` is not installed (or if it's version that is incompatible with the types we export, TypeScript will complain:

```ts
import ReactRefreshWebpackPlugin from "@pmmmwh/react-refresh-webpack-plugin";

const config = {
	plugins: [
		new ReactRefreshWebpackPlugin({
			// ^ This line will complain given you does not have `skipLibraryTypes: true` set
			// some options ...
		});
	],
};

export default config;
```

**Comment by tianyingchun** [comment] 2023-08-11 05:45
if so you can add it as `dependencies` not peerDependencies

**Comment by ankhzet** [comment] 2023-08-11 07:09
@pmmmwh Seems to be working fine in my code. Is it IDE/LSP-dependant issue, or may it be that your knowledge is based on an old misunderstanding? 
! **It is likely, tho,** that the types are correctly resolving for me because the version of type-fest i use (4.1) is compatible with what this package uses, and may, in fact, break if interface-wise incompatible version is used (didn't try with 5.0+ yet).
My point will still stand in this case, with an addition: if it's compatible - at least wildcard it, only restrict to a specific range, when it becomes known to be incompatible. Peer dependencies are already a hassle to deal with %).

![packagejson](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/6272356/227722ef-55a2-4708-8a88-4a94f395e31b)
![installedpackage](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/6272356/dea125ce-e671-427a-9ce1-1ae8ad53bb9b)
![import](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/6272356/c4420a2a-a919-48a0-b3a1-e32af7d9071a)
![usage](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/6272356/ca5e6dbf-7527-4a0b-a452-5e5b85cfa451)

**Comment by pmmmwh** [comment] 2023-08-14 09:14
> if so you can add it as dependencies not peerDependencies , or upgrade type-fest to V4 @:)

It is an **optional** dependency that we **loosly** depend on (e.g. if you don't use TypeScript?), optional peer dependencies are designed exactly for this purpose.

> It is likely, tho, that the types are correctly resolving for me because the version of type-fest i use (4.1) is compatible with what this package uses, and may, in fact, break if interface-wise incompatible version is used (didn't try with 5.0+ yet).

That is exactly my point - if you **don't** have it installed it will break, and that's why it is a **peer** dependency because we don't strongly care what version you use, but it is also **optional** because you have to opt-in to this TS feature.

> My point will still stand in this case, with an addition: if it's compatible - at least wildcard it, only restrict to a specific range, when it becomes known to be incompatible.

That's not how dependencies should work - when it is known to be incompatible it would have already broke people's configurations, and that is not the kind of behaviour I would like to see; `type-fest` in general does not release a lot of major versions, so I think it is an acceptable trade-off to once in a while bump the version - in fact, PRs are always welcome. I know it can cause some hassle but you can always override things via `resolutions` on `yarn` (I believe there are equivalent constructs in `npm`).

**Closed** 2023-08-14 09:24 UTC
