### ISSUE TITLE
$RefreshReg$ is not defined

### ISSUE THREAD

**Issue by samaneh-kamalian** [pmmmwh/react-refresh-webpack-plugin#397] opened 2021-05-22 09:15 UTC
I use React native for an application for android and ios. now I want publish my app for web . So I use webpack to create bundle and use in react structure. but my problem is that for any changes in my code, I must create bundle with `webpack`
command and it takes long time for see the affect of my changes. 
So I use your plugin but` $RefreshReg$ is not defined` error occurred.
I follow your Troubleshooting, but none of the solutions work for me.
this is my webpack.conf.js:

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

const path = require('path');
const webpack = require('webpack');

const isDevelopment = process.env.NODE_ENV !== 'production';

module.exports = {
  mode: 'development',
  //entry: './src/index.js',
  entry: [
    // 'babel-polyfill', 
    './src/index.js'
  ],
  output: {
    path: path.resolve(__dirname, 'release'),
    filename: 'bundle.js',
    publicPath: '/release/'
  },

  // Enable source map support
  devtool: 'source-map',
  plugins: [
    new HtmlWebpackPlugin({
    title: 'PWA',
    }),
    new webpack.DefinePlugin({ process: { env: {} } }),
    isDevelopment && new webpack.HotModuleReplacementPlugin(),
    isDevelopment && new ReactRefreshWebpackPlugin(),
    ].filter(Boolean),
  // Loaders and resolver config
  module: {
    rules: [
        {
          test: /react-native-reanimated|react-native-gesture-handler|react-native-material-ui|react-native-vector-icons|react-native-countdown-circle|react-native-version-number|react-native-loading-spinner-overlay|react-native-material-menu|react-native-swiper|react-native-animatable|react-native-qrcode-scanner|react-native-share|react-native-swipe-list-view|react-native-color-palette|react-native-ok-gesture-password|react-native-walkthrough-tooltip|react-native-camera|react-native-fs|react-native-keychain|react-native-push-notification|react-navigation-header-buttons/,
          exclude: [
            /.(json)$/
          ],
          use: {
            loader: "babel-loader",
            options: {
              presets: [
                "babel-preset-expo"
              ],
            },
          },
        },
        {
            test: /.(js|jsx)$/,
            include: [
              path.resolve(__dirname,'./src'),
            ],
            use: {
              loader: 'babel-loader',
              options: {
                presets: [
                  '@babel/preset-env',
                  '@babel/preset-react',
                  //'@babel/preset-flow',
                 // "@babel/preset-typescript"
                 
                ],
                 plugins: [
                //   'babel-plugin-react-native-web',
                   '@babel/plugin-proposal-class-properties',
                //   '@babel/plugin-proposal-object-rest-spread',
                isDevelopment && require.resolve('react-refresh/babel')
                 ].filter(Boolean),
              },
            },
        },
        {//for displaying images in onboarding page, add this loader and remove file-loader
          test: /\.(jpg|png|woff|woff2|eot|ttf|svg|jpeg)$/,
          use: {
            loader: "url-loader",
            options: {
              name: "[name].[ext]",
              esModule: false,
            }
          }
        
        }
    ],
  },
  resolve: {
    alias: {
        'react-native$': require.resolve('react-native-web'),
      },
    extensions: [".webpack.js", ".web.js", ".ts", ".js"]
  },
  plugins: [
    // Add __DEV__ flag to browser example.
    new webpack.DefinePlugin({
      __DEV__: process.env,
    }),
  ],

  // Development server config
  devServer: {
    contentBase: path.join(__dirname, 'release'),
    compress: true,
    port: 2000,
    historyApiFallback: true,
  },
};
```

**Comment by pmmmwh** [comment] 2021-06-01 21:55
Are you sure your files are processed by the plugin? Can you create a reproduction?

**Comment by 0xdeafcafe** [comment] 2021-06-02 12:42
We had this awhile ago, are you sure `NODE_ENV` is being set?

**Comment by pmmmwh** [comment] 2021-07-11 23:55
Closing - cannot reproduce and is likely due to `NODE_ENV` being unset.

**Closed by pmmmwh** 2021-07-11 23:55 UTC
