### ISSUE TITLE
RejectionHandler error occurs every time I make change to a file

### ISSUE THREAD

**Issue by utkarsh-1mg** [pmmmwh/react-refresh-webpack-plugin#373] opened 2021-04-25 15:11 UTC
Everytime I try to update a file in I am getting the following error.

![Screenshot 2021-04-25 at 6 58 15 PM](https://user-images.githubusercontent.com/72802525/115995261-32f01780-a5f8-11eb-86f0-48e386dc6336.png)

I have the following webpack configuration:

babel.config.client.js
```
export default {
    babelrc: false,
    presets: [
        [
            "@babel/preset-env",
            {
                targets: {
                    browsers: "last 2 versions",
                },
            },
        ],
        "@babel/preset-react",
    ],
    plugins: [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-transform-react-jsx",
        "transform-es2015-modules-commonjs",
        "@loadable/babel-plugin",
        "transform-class-properties",
        "transform-export-extensions",
        "syntax-dynamic-import",
    ],
    env: {
        development: {
            plugins: [require.resolve("react-refresh/babel")],
        },
        production: {
            plugins: ["transform-react-remove-prop-types"],
        },
    },
}
```

babel.config.ssr.js

```
export default {
    babelrc: false,
    presets: [
        [
            "@babel/preset-env",
            {
                targets: {
                    node: "current",
                },
            },
        ],
        "@babel/preset-react",
    ],
    plugins: [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-transform-react-jsx",
        "@loadable/babel-plugin",
        "transform-es2015-modules-commonjs",
        "transform-class-properties",
        "transform-export-extensions",
        "syntax-dynamic-import",
    ],
    env: {
        development: {
            plugins: [require.resolve("react-refresh/babel")],
        },
        production: {
            plugins: ["transform-react-remove-prop-types"],
        },
    },
}
```

base.babel.js

```
import yn from "yn"
import path from "path"
import webpack from "webpack"
import MiniCssExtractPlugin from "mini-css-extract-plugin"
import { BundleAnalyzerPlugin } from "webpack-bundle-analyzer"
import LoadablePlugin from "@loadable/webpack-plugin"
import mapValues from "lodash/mapValues"
import keyBy from "lodash/keyBy"
import filter from "lodash/filter"
const Dotenv = require("dotenv-webpack")

import scssParams from "./scssParams"
import { _moduleAliases } from "../package.json"
import babelOpts from "./babel.config.client"
import { enableDynamicImports, clientEnv, cssModulesIdentifierDev, cssModulesIdentifierProd } from "../config"

require("../scripts/loadEnvironmentVariables")()

const isDev = process.env.NODE_ENV !== "production"
const cwd = process.cwd()

export const isSSR = yn(process.env.SSR) || false
export const analyzeBundle = yn(process.env.ANALYZE) || false
export const basePlugins = {
    loadableComponents: new LoadablePlugin({
        filename: path.join(__dirname, "..", "loadable-stats.json"),
        writeToDisk: true,
    }),
    miniExtractPlugin: new MiniCssExtractPlugin({
        filename: "[name].[contenthash].css",
    }),
    definePlugin: new webpack.DefinePlugin({
        "process.env": mapValues(keyBy(clientEnv), (env) => {
            return JSON.stringify(process.env[env])
        }),
        // Loadable dynamic rendring config
        "process.loadableConfig": {
            CLIENT_ONLY_RENDER: process.env["CLIENT_ONLY_RENDER"] === "true",
            SERVER_SIDE_RENDER: process.env["SERVER_SIDE_RENDER"] === "true",
        },
    }),
    bundleAnalyzerPlugin: new BundleAnalyzerPlugin(),
    dotEnvPlugin: new Dotenv(),
    ignorePlugin: new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
}

const allowedPlugin = (plugin, key) => {
    switch (key) {
        case "loadableComponents":
            return enableDynamicImports
        case "miniExtractPlugin":
            return !isSSR
        case "bundleAnalyzerPlugin":
            return analyzeBundle
        default:
            return true
    }
}

const publicPath = isDev
    ? process.env.PUBLIC_ASSET_PATH || "/"
    : `${process.env.CDN_ASSET_PATH}/${process.env.S3_FOLDER}/${process.env.BUILD_ENV}/`
console.log("public path:", publicPath)

export default {
    context: path.resolve(__dirname, ".."),
    mode: isDev ? "development" : "production",
    entry: {
        app: ["./client/index"],
    },
    optimization: {
        runtimeChunk: "single",
        moduleIds: "deterministic",
        splitChunks: {
            cacheGroups: {
                vendor: {
                    name: "vendors",
                    chunks: "all",
                    reuseExistingChunk: true,
                    priority: 1,
                    enforce: true,
                    // extract to vendor chunk if it's in /node_modules
                    test: (module) => /node_modules/.test(module.context),
                },
            },
        },
    },
    output: {
        path: path.join(__dirname, "..", process.env.PUBLIC_OUTPUT_PATH),
        filename: "[name].bundle.js",
        publicPath: process.env.PUBLIC_ASSET_PATH || "/",
        chunkFilename: enableDynamicImports ? "[name].bundle.js" : undefined,
    },
    resolve: {
        extensions: [".js", ".jsx", ".scss"],
        alias: mapValues(_moduleAliases, (aliasPath) => path.join(cwd, ...aliasPath.split("/"))),
    },
    plugins: filter(basePlugins, allowedPlugin),
    module: {
        rules: [
            {
                test: /\.jsx$|\.js$/,
                exclude: /node_modules/,
                loader: "babel-loader",
                options: babelOpts,
            },
            {
                // For all .scss files that should be modularized. This should exclude
                // anything inside node_modules and everything inside src/css/base
                // since they should be globally scoped.
                test: /\.scss$/,
                exclude: [
                    path.resolve(__dirname, "../node_modules"),
                    path.resolve(__dirname, "../src/static/css/base"),
                ],
                use: [
                    "css-hot-loader",
                    MiniCssExtractPlugin.loader,
                    {
                        loader: "css-loader",
                        options: {
                            modules: {
                                compileType: "module",
                                mode: "local",
                                localIdentName: isDev ? cssModulesIdentifierDev : cssModulesIdentifierProd,
                            },
                            importLoaders: 1,
                        },
                    },
                    { loader: "postcss-loader" },
                    {
                        loader: "sass-loader",
                        options: {
                            functions: {
                                "url_for($key)": scssParams.urlFor,
                                "font_url($key)": scssParams.fontUrl,
                            },
                        },
                    },
                    {
                        loader: "sass-resources-loader",
                        options: {
                            resources: ["./src/static/css/resources/*.scss"],
                        },
                    },
                ],
            },
            {
                // for .scss modules that need to be available globally, we don't pass
                // the files through css-loader to be modularized.
                test: /\.scss$/,
                include: [
                    path.resolve(__dirname, "../node_modules"),
                    path.resolve(__dirname, "../src/static/css/base"),
                ],
                use: [
                    "css-hot-loader",
                    MiniCssExtractPlugin.loader,
                    { loader: "css-loader" },
                    { loader: "postcss-loader" },
                    {
                        loader: "sass-loader",
                        options: {
                            functions: {
                                "url_for($key)": scssParams.urlFor,
                                "font_url($key)": scssParams.fontUrl,
                            },
                        },
                    },
                    {
                        loader: "sass-resources-loader",
                        options: {
                            resources: ["./src/static/css/resources/*.scss"],
                        },
                    },
                ],
            },
            {
                test: /\.css$/,
                use: [MiniCssExtractPlugin.loader, "css-loader", "postcss-loader"],
            },
            {
                test: /\.(png|jpg|gif|jpeg|ico|svg?)$/,
                use: ["url-loader?limit=10240", "img-loader"],
            },
            {
                // Load fonts using file-loader
                test: /\.(ttf|eot|woff2|json?)$/,
                use: [
                    {
                        loader: "url-loader",
                        options: {
                            limit: 10240,
                            outputPath: "/src/static/fonts/",
                        },
                    },
                    "file-loader",
                ],
            },
            {
                // Load html files
                test: /\.html$/,
                use: [
                    {
                        loader: "html-loader",
                        options: {
                            minimize: true,
                            removeComments: false,
                            collapseWhitespace: true,
                        },
                    },
                ],
            },
        ],
    },
}
```

development.client.babel.js 

```
/* eslint-disable no-console */
import WebpackDevServer from "webpack-dev-server"
import webpack from "webpack"
import merge from "webpack-merge"
import baseConfig from "./base.babel.js"
const ReactRefreshWebpackPlugin = require("@pmmmwh/react-refresh-webpack-plugin")

const { DEV_SERVER_PORT, DEV_SERVER_HOSTNAME, DEV_SERVER_HOST_URL } = process.env

const webpackConfig = merge(baseConfig, {
    devtool: "eval",
    entry: {
        app: ["webpack-dev-server/client?" + DEV_SERVER_HOST_URL, "webpack/hot/only-dev-server"],
    },
  
   plugins: [new ReactRefreshWebpackPlugin()],
})

console.info("Firing up Webpack dev server...\n")

new WebpackDevServer(webpack(webpackConfig), {
    port: process.env.DEV_SERVER_PORT,
    publicPath: webpackConfig.output.publicPath,
    hot: true,
    historyApiFallback: true,
    noInfo: false,
    quiet: false,
    headers: { "Access-Control-Allow-Origin": "*" },
    stats: {
        colors: true,
        hash: false,
        version: false,
        chunks: false,
        children: false,
    },
    disableHostCheck: true,
}).listen(DEV_SERVER_PORT, DEV_SERVER_HOSTNAME, (e) => {
    if (e) {
        console.error(e)
    } else {
        console.info(`Webpack dev server mounted at ${DEV_SERVER_HOST_URL}.`)
    }
})
```

**Comment by pmmmwh** [comment] 2021-04-25 17:26
Do you have any unhandled promises? What does it show in the console?

**Comment by utkarsh-1mg** [comment] 2021-04-25 18:48
@pmmmwh I checked the console. The API calls fails because my node server restarts everytime I make changes to my code. 
On node I am watching loadable-stats.json and whenever this file changes my node server restarts.

**Comment by pmmmwh** [comment] 2021-04-25 21:22
Then the error seems to be firing correctly because there is indeed an unhandled promise rejection?
What API calls are failing?

**Comment by pmmmwh** [comment] 2021-06-04 21:28
Closed as it seems to be working as intended and reporting actual HTTP call failures.

If you want to avoid this issue, maybe you could add a catch clause to your API calls.

**Closed by pmmmwh** 2021-06-04 21:28 UTC
