### ISSUE TITLE
Hot loading can't successfully work

### ISSUE THREAD

**Issue by scattter** [pmmmwh/react-refresh-webpack-plugin#322] opened 2021-03-02 01:37 UTC

**Comment by scattter** [comment] 2021-03-02 02:11
#### Project structure is bellow

-- build

------- dllHHelper.js

------- webpack.base.config.js

------- webpack.build.config.js

------- webpack.dll.config.js

------- webpack.local.config.js

-- src

------- App.tsx

------- Index.tsx

-- .env.js

-- bable.config.js

-- package.json



#### Detail config:

- Index.tsx

```javascript
if (ENV_NAME === 'prod') {
  extendedWindow.NREUM.loader_config = NEW_RELIC_CONFIG.PROD.loader_config
  extendedWindow.NREUM.info = NEW_RELIC_CONFIG.PROD.info
} else if (ENV_NAME !== 'local') {
  extendedWindow.NREUM.loader_config = NEW_RELIC_CONFIG.NON_PROD.loader_config
  extendedWindow.NREUM.info = NEW_RELIC_CONFIG.NON_PROD.info
}

NP.enableBoundaryChecking(false)

ReactDOM.render(<App />, document.getElementById('root'))
```



- App.js

```javascript
const FeaturedApp: React.FC<Props> = ({ initEndpointRegion }) => {
  const initEndpointByRegion = () => {
    const currentRouterUrl = window.location.href
    if (currentRouterUrl.indexOf('login-loading') === -1) return

    const locationSearch = currentRouterUrl.split('?')[1]
    const { region } = getUrlParams(locationSearch)
    initEndpointRegion(region as EndpointRegion)
  }

  useEffect(() => {
    initEndpointByRegion()
  }, [])

  return (
    // ....
  )
}

const FeaturedAppContainer = connect(
  null,
  mapDispatchToProps,
)(FeaturedApp)

const App = () => (
  <Provider store={store}>
    <FeaturedAppContainer />
  </Provider>
)

export default App
```



- webpack.local.config

```javascript
const path = require('path')
const axios = require('axios')
const webpack = require('webpack')
const merge = require('webpack-merge')
const common = require('./webpack.base.config')
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin')
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin')
const FriendlyErrorsWebpackPlugin = require('friendly-errors-webpack-plugin')
const ReactRefreshPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

const PORT = 2223
const _HOST = '0.0.0.0'
const HOST = `http://${_HOST}`
const URL = `${HOST}:${PORT}`
const endpointRegion = {
  apac: 'apac',
  cyprus: 'cyprus',
}
const ENDPOINT_REGION = endpointRegion.apac

module.exports = merge(common, {
  mode: 'development',
  // developer click error logs that in chrome console can directly reach original code
  devtool: 'eval-source-map',
  devServer: {
    stats: {
      colors: true,
      modules: false,
      children: false,
      chunks: false,
      chunkModules: false,
    },
    inline: true,
    injectHot: true,
    quiet: true,
    hot: true,
    // enable HMR on the server
    compress: true,
    contentBase: path.resolve(__dirname, '../src'),
    // match the output path
    port: PORT,
    host: _HOST,
    publicPath: URL,
    historyApiFallback: true,
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    openPage: 'start',
    before: function(app) {
      // const getToken = ....
    }
  },
  module: {
    rules: [
      {
        test: /\.tsx$/,
        exclude: /node_modules/,
        use: {
          loader: require.resolve('babel-loader'),
          options: {
            presets: ['@babel/env', '@babel/preset-react'],
            plugins: [require.resolve('react-refresh/babel')], // add react-refresh
          },
        }
      },
    ],
  },
  plugins: [
    new ReactRefreshPlugin(),    // add react-refresh
    new FriendlyErrorsWebpackPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new ForkTsCheckerWebpackPlugin(),
    new HardSourceWebpackPlugin(),
  ],
})

```



- babel.config

```
module.exports = {
  plugins: [
    'lodash',
    '@babel/plugin-transform-runtime',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['import', { libraryName: 'antd', style: true }],
  ],
  presets: [
    ['@babel/preset-env', { targets: { browsers: 'last 2 versions' } }],
    '@babel/preset-typescript',
    '@babel/preset-react',
  ]
}
```



- package.json

```javascript
{
    "name": "txxxxx",
    "version": "xxxxx",
    "description": "xxxx",
    "main": "index.js",
    "repository": "https://xxxxxx",
    "scripts": {
        "start": "env-cmd -r .env.js -e local webpack-dev-server --config build/webpack.local.config.js --open",
        "build:dev": "env-cmd -r .env.js -e dev npm run build",
        "build:qa": "env-cmd -r .env.js -e qa npm run build",
        "build:uat": "env-cmd -r .env.js -e uat npm run build",
        "build:stg": "env-cmd -r .env.js -e stg npm run build",
        "build:prod": "env-cmd -r .env.js -e prod npm run build",
}
```





- Relation dependences
  - "react": "16.13.0"
  - "react-dom": "16.13.0"
  - "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
  - "@types/react-dom": "^16.9.6"
  - "webpack": "^4.30.0"
  - "webpack-ant-icon-loader": "^1.0.5"
  -  "webpack-bundle-analyzer": "^3.3.2"
  -  "webpack-cli": "^3.3.1"
  - "webpack-dev-middleware": "^3.6.2"
  - "webpack-dev-server": "^3.3.1"
  - "webpack-hot-middleware": "^2.24.4"
  - "webpack-merge": "^4.2.1"

**Comment by pmmmwh** [comment] 2021-03-02 20:03
Can you provide a bit more information on how it is not working?

**Comment by scattter** [comment] 2021-03-03 07:48
> Can you provide a bit more information on how it is not working?

Web page will not refresh when some code change in our project except forced  refresh.

Console info is below:
[WDS] App updated. Recompiling...
client?e01c:303 [WDS] App hot update...
log.js?1afd:24 [HMR] Checking for updates on the server...
log.js?1afd:24 [HMR] Updated modules:
log.js?1afd:24 [HMR]  - ./src/pages/mass-offer/list/index.tsx
log.js?1afd:24 [HMR] App is up to date.

**Comment by athomann** [comment] 2021-03-29 04:56
I noticed you have ` webpack.dll.config.js` You don't happen to be using `DllPlugin` and `DllReferencePlugin` ?  I noticed that hot loading doesn't work with those plugins.  When I remove them, it starts working again.

**Comment by pmmmwh** [comment] 2021-03-29 08:58
So I'm not quite sure why DLL would break this - my gut feeling is that `react-refresh/runtime` did not run before any React code (`react`, `react-dom`). Probably tweaking the configuration of the DLL would help?

**Comment by athomann** [comment] 2021-03-29 14:48
Looks like I was able to get it working by switching to dev mode in the DLL web pack settings.

**Comment by eliseumds** [comment] 2021-04-01 04:19
@athomann what do you mean by `switching to dev mode in the DLL web pack settings`? Would you please share your Webpack config with us?

**Comment by pmmmwh** [comment] 2021-04-01 13:17
You can specify `mode: 'development'` in the Webpack configuration of the DLL?

**Comment by athomann** [comment] 2021-04-01 14:04
Yes, that's what I was referring to.

**Comment by pmmmwh** [comment] 2021-05-14 21:28
Troubleshooting guide have been updated with instructions to set `mode: 'development'` - I'll close this for now as a solution seemingly was found and I cannot reproduce anymore.

**Closed by pmmmwh** 2021-05-14 21:28 UTC

**Comment by tianwawawa** [comment] 2021-12-06 07:01
hmr incompatibel with antd(https://github.com/ant-design/ant-design/).  TypeError: Cannot read property 'call' of undefined

**Comment by pmmmwh** [comment] 2021-12-11 21:00
> hmr incompatibel with antd([ant-design/ant-design](https://github.com/ant-design/ant-design/)). TypeError: Cannot read property 'call' of undefined

Can you create a reproducible example? Where does the error show up? What version of this plugin/webpack/dev server are you using?

**Comment by tianwawawa** [comment] 2021-12-13 01:36
// 1 code
App.tsx
`import React, { lazy, Suspense } from 'react';
const Hello = lazy(()=>import('./hello'))


export default function App () {
    return (
        <div>
            <Suspense fallback={<div>load---</div>}>
                <Hello />
            </Suspense>
        </div>
    )
}`

Hello.tsx
`import React from 'react';
import { Button, Space } from 'antd'
const Hello= ()=> {
  return (
    <Space>
       <Button>test</Button>
    </Space>
  )
}

export default Hello`
// 2 version
"@pmmmwh/react-refresh-webpack-plugin": "0.5.1",
 "react-refresh": "^0.10.0",
 "webpack": "^5.53.0",
  "webpack-cli": "^4.7.2",
  "webpack-dev-server": "^4.2.1",
  "webpack-merge": "^5.8.0"
  "@babel/plugin-transform-runtime": "7.7.6",
  ....
// 3 error
change the <Space> with other component every time 
import { Button, **Card**, Space } from 'antd';
import React from 'react';
const Hello= ()=> {
  return (
    <**Card**>
       <Button>test</Button>
       <Space>22</Space>
    </**Card**>
  )
}

export default Hello
// 
<img width="1192" alt="Screen Shot 2021-12-13 at 9 30 57 AM" src="https://user-images.githubusercontent.com/17872613/145739203-f13a15fe-2ba1-4857-af1d-7558629d84bb.png">

if you refresh the whole page,  the error dispear !

(In face, I tried many versions of antd   webpack-dev-server  @pmmmwh/react-refresh-webpack-plugin the bug still there )
