### ISSUE TITLE
[TypeScript] Refresh not working with arrow functions

### ISSUE THREAD

**Issue by XavierAgostini** [pmmmwh/react-refresh-webpack-plugin#365] opened 2021-04-22 18:33 UTC
Hey There,

I'm running into issues getting hot reloading working in my webpack-typescript app:

![image](https://user-images.githubusercontent.com/7476817/115766761-2e5c0280-a35d-11eb-9332-8c0afa11e1f9.png)

I'm only getting this error when I use arrow functions to declare my React components:

```
// hot-reload doesn't work
const App = () => {
  return ....
}
export default App

// hot-reload works
function App () {
  return ...
}
export default App;
```

This approach works when I use the sample project though.
> https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/217

```
 plugins: [
    new ReactRefreshPlugin(),
    new ForkTsCheckerWebpackPlugin(),
    new HtmlWebpackPlugin({
      filename: './index.html',
      template: './public/index.html',
    }),
  ]
```

Dependencies:
```
"fork-ts-checker-webpack-plugin": "^6.0.6",
"html-webpack-inline-source-plugin": "^0.0.10",
"html-webpack-plugin": "^4.4.1",
"react-refresh": "^0.9.0",
"react-refresh-typescript": "^1.1.0",
"style-loader": "^0.23.1",
"ts-loader": "^8.0.4",
"webpack-cli": "^3.3.12",
"webpack-dev-server": "^3.11.0",
```

Any ideas on what is causing this issue?

**Comment by tundaey** [comment] 2021-04-26 14:31
I'm having the exact same issue. HMR doesn't work for arrow function components

**Comment by pmmmwh** [comment] 2021-04-26 18:31
What version of this plugin are you using? Can you try `2.0.0` of `react-refresh-typescript`?

**Comment by tundaey** [comment] 2021-04-27 13:25
Hi, I'm using the same versions of the packages you listed. Here's my config

package.json 

```
"scripts": {
    "start": "webpack serve --mode development",
    "build": "webpack --mode production",
    "test": "echo Skipped for now.",
    "bundle-report": "webpack-bundle-analyzer --port 4200 compilation-stats.json",
    .......
    "react-refresh": "^0.10.0",
    "react-refresh-typescript": "^2.0.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
},
```

webpack.config.js
```
module.exports = {
	entry: './src/index.tsx',
	target: 'web',
	resolve: {
		extensions: ['.ts', '.tsx', '.js'],
		plugins: [
			new TsconfigPathsPlugin(),
		],
		alias: {
			'~website': path.resolve(__dirname, './src'),
			'~lib': path.resolve(__dirname, '../../lib/src'),
		},
	},
	output: {
		path: path.join(__dirname, 'dist'),
		publicPath: '/',
		filename: '[name].[contenthash].js',
		clean: true,
	},
	module: {
		rules: [{
			test: /\.(j|t)sx?$/,
			exclude: /node_modules/,
			use: [{
				loader: 'ts-loader',
				options: {
					projectReferences: true,
					happyPackMode: true, // This implicitly sets "transpileOnly" to be true anyway
					transpileOnly: true,
					getCustomTransformers: () => ({
						before: isDevelopment ? [ReactRefreshTypeScript()] : [],
					  }),
					  compilerOptions: {
						  module: 'esNext',
					  },
				},
			}],

		}, {
			test: /\.s[ac]ss$/i,
			use: [
				'style-loader',
				'css-loader',
				'sass-loader',
			],
		}, {
			test: /\.svg$/i,
			loader: '@svgr/webpack',
		}],
	},
	plugins: [
		new ForkTsCheckerWebpackPlugin({
			typescript: {
				diagnosticOptions: {
					semantic: true,
					syntactic: true,
				},
			},
		}),
		new webpack.EnvironmentPlugin(envVars),
		new NodePolyfillPlugin(),
		new HtmlWebpackPlugin({
			template: path.join(__dirname, 'index.html'),
			filename: 'index.html',
		}),
		new CopyPlugin([
			{ from: 'public' },
		]),
    	isDevelopment && new ReactRefreshWebpackPlugin(),
	].filter(Boolean),
	cache: {
		type: 'filesystem',
		cacheDirectory: path.resolve(__dirname, '.webpack-cache'),
	},
	devServer: {
		historyApiFallback: true,
		publicPath: '/',
		contentBase: path.resolve(__dirname, 'public'),
		port: 3000,
		hotOnly: true,
		liveReload: false,
	},
	devtool: 'eval-cheap-source-map',
};
```

**Comment by XavierAgostini** [comment] 2021-04-27 14:38
The weird thing i've noticed, is that arrow functions work, but they just can't be used as the entry component into my app. I'll try those updated versions later today.

**Comment by Ogg70** [comment] 2021-05-21 10:25
Hi, I have exactly the same problem, but I have come to the conclusion that the arrow functions do not have to do with it. As far as I understand, it's all about the use of hooks.

```
// hot-reload works
// displayName in React Developer Tools - App
const App = () => {
  return <div><button>add</button></div>;
};

export default App;
```

```
// hot-reload doesn't work(triggered full reload)
// displayName in React Developer Tools - Anonymous
const App = () => {
  const [count, setCount] = React.useState(1)
  return <div><button onClick={() => setCount(count + 1)}>add</button></div>;
};

export default App;
```

I also noticed that in React Developer Tools, the arrow function components are named `<Anonymous>`.
Most likely the problem is in [react-refresh-typescript](https://github.com/Jack-Works/react-refresh-transformer/tree/main/typescript), for some reason the component loses displayName.

**Comment by Jack-Works** [comment] 2021-05-21 14:26
> The weird thing i've noticed, is that arrow functions work, but they just can't be used as the entry component into my app. I'll try those updated versions later today.

Yes, there is a report in https://github.com/Jack-Works/react-refresh-transformer/issues/2 that the root of the whole app cannot be HMR updated but I have not investigated that because IMO most of the development happens in the non-root components.

**Comment by Jack-Works** [comment] 2021-05-23 15:04
I tried to reproduce this and found it's likely not a bug in `react-refresh-transformer`.

If `used as entry component` means the following code:

```jsx
import { render } from 'react-dom'
import { Component } from './Component'

export function App() {
    return (
        <div>
            <Component />
        </div>
    )
}
render(<App />, document.getElementById('root')!)
```

Yes, in this case, it won't refresh but reload the whole tree. Because every time this file getting HMRed, this whole file will be re-executed. And if you re-call `ReactDOM.render` (the last line) on your root component, it will be unmounted and remounted, because the previous `App` has a different identity than the current `App`, and the reconciliation algorithms will not diff the vDOM tree for a different component tree.

If it is your case, please move `App` to another file, that will fix the problem. If not, please point out and give a reproduce. Thanks

**Comment by pmmmwh** [comment] 2021-05-30 23:00
Closed as things seem to be working as intended.
If there are new issues or other reproductions feel free to open a new issue.

**Closed by pmmmwh** 2021-05-30 23:00 UTC

**Comment by dimitriirybakovparsable** [comment] 2021-07-12 09:21
@Ogg70 did you resolve your problem? I have exact same issue

**Comment by Jack-Works** [comment] 2021-07-12 15:15
I confirmed this is a bug, fixed in 2.0.2, please try it.

**Comment by xiaomitangtang** [comment] 2023-09-17 13:05
1、   export default ()=><>xxxxx</>

2、  const A=()=><>xxxx</>
        export default A 

3、export default function A(){}

4、export default class A{}


only  1   is not work   with hot update


2、3、4 worked with hot update

is like a bug with export default arrow function

**Comment by Jack-Works** [comment] 2023-09-17 18:03
if you're using react-refresh-typescript, please open an issue in https://github.com/Jack-Works/react-refresh-transformer/
