### ISSUE TITLE
after version 0.3.3 components refreshing stoped working

### ISSUE THREAD

**Issue by AlexKund** [pmmmwh/react-refresh-webpack-plugin#220] opened 2020-10-02 09:33 UTC
Our project is ruby/rails and we use react_on_rails for react
with react-refresh-webpack-plugin v 0.3.3 we don't have any troubles with hmr but after updating to version 0.4.2 state changes in components for example stopped refreshing. In below example if I change **btnDisabled** to true it doesnt reflect in browser:
```javascript
  constructor(props) {
    super(props);

    this.state = {
      messageIsVisible: false,
      btnDisabled: false,
      passwordIsVisible: false
    };
  }
```
Actually if I add console.log to jsx file, but outside component, and change it content, for example from 'test1' to 'test2'  browser console reflect that change. I could provide with video to show the issue

**Comment by pmmmwh** [comment] 2020-12-31 19:07
Hi - is it possible to provide a reproduction repo so I can dig into it?

**Comment by pmmmwh** [comment] 2021-04-24 22:30
Unable to reproduce in the latest version, closing for now.

**Closed by pmmmwh** 2021-04-24 22:30 UTC
