### ISSUE TITLE
Local state not preserved

### ISSUE THREAD

**Issue by pongstylin** [pmmmwh/react-refresh-webpack-plugin#416] opened 2021-06-03 17:08 UTC
So, I've been having a devil of a time trying to get local state to be preserved when hot reloading modules.  I started out with react-hot-loader without success.  And now I'm trying react-refresh.  I converted my app to use functional component syntax and reviewed the troubleshooting guide.  The part that talks about splitting chunks caught my attention as a possible cause.  But I have 3 questions that all relate to preservation of state:

1. I have a fairly exotic webpack config with multiple entry points where each entry point is a different app.  I expect `optimization.runtimeChunk.name = 'runtime-common'` to be acceptable.  But I'm not sure if `optimization.splitChunks.chunks = 'all'` is acceptable.  The troubleshooting guide just mentions explicitly creating an entry point for vendors.  But I'm letting splitChunks dynamically create that bundle.  Does that need to change?
2. Also, since my development HTML page embeds all bundles into the same page, I've written some code that enables switching between apps.  I've manually configured "module.hot.accept" to allow me to maintain a reference to the latest and greatest app across hot reloads and rerender appropriately.  Do you expect this to conflict with react-refresh and, if so, how would I make them work together?  Basically, I don't need to manually rerender the app using ReactDOM when a hot reload occurs if 'react-refresh' handles that, but I need a reference to the updated app component in the event I switch to a different app and back.
3. Finally, I'm using a 3rd-party component library that uses class components.  Do you expect any issues where class components (as a parent or child) to cause functional components to fail to preserve state?

I'm using React 16.9 and webpack 4.  If you need any further details, just let me know.  I'd rather not create a whole new Git repository to make a publicly accessible reproduction, but will if I must.

**Comment by pmmmwh** [comment] 2021-06-05 00:31
For 1 - as long as React, React-DOM and React-Refresh are in the same chunk it should be quite safe.

For 2 - it would likely conflict. This plugin taps into Webpack's HMR lifecycle to achieve HMR. Anything that hits the root of a entry would be an automatic bail out for RR and we do not handle calling `ReactDOM.render` again on HMR updates. However if you scope your custom HMR logic to app roots only anything beneath that should still be supported.

For 3 - All components are their own unit, so no. However the class components will not preserve state.

**Comment by pongstylin** [comment] 2021-06-05 00:46
Very well.  None of what you say is clueing me to the problem so I will create a new repo, start with something basic / working, and evolve it closer and closer to what I have until it breaks.  If that doesn't tell me what is wrong, I can have you look at it.  Fair?

**Comment by pmmmwh** [comment] 2021-06-07 13:47
Yes, if you can provide a reproduction I can look at it and see what could possibly be wrong.

**Comment by pongstylin** [comment] 2021-06-07 16:06
Alright, I've narrowed it down to the babel config.  Since I'm building the app using Instructure UI components, I'm using the babel config that they recommend with that.  However, it is breaking the preservation of state.  When I attempt to move their babel config into my local project, state is suddenly preserved.  So there is something that I am not imitating correctly.  In any case, perhaps you can look at it and more easily determine the problem based on your familiarity with react-refresh.

Here's a repository with 2 commits.  The first commit is working, the 2nd isn't.
https://github.com/pongstylin/rrtest

**Comment by pmmmwh** [comment] 2021-06-07 22:46
I've tested and it seems like the project works as expected using `0.5.0-rc.0` of this plugin, and `0.10.0` or React Refresh. Would you mind trying them? `0.5.0` will be published soon (probably this weekend) once I finish some final cleanup and documentation tasks.

**Comment by pongstylin** [comment] 2021-06-07 23:55
I skipped right past testing it in the reproduction project and went into my origin project and simply upgraded those two packages as you suggested and it immediately worked.  Thank you very much.

I still don't know why I couldn't get react-hot-loader working, but it is a more convoluted setup and am not sure if preserving state for class components will be a necessity at this time.

**Comment by AaronBuxbaum** [comment] 2021-06-09 00:52
I'm running `0.5.0-rc.0` and `0.10.0` and experiencing the same loss of state; everything else is working perfectly. How can I debug what's going on?

**Comment by pmmmwh** [comment] 2021-06-09 21:37
@AaronBuxbaum Is the page always force refreshing, or is it updating but without persisting state?

**Comment by AaronBuxbaum** [comment] 2021-06-09 21:48
> @AaronBuxbaum Is the page always force refreshing, or is it updating but without persisting state?

The latter -- if I have the most basic functional component I could come up with...
```
function Test() {
  const [count, setCount] = useState(0);

  return <button onClick={() => setCount(count+1)}>{count}</button>
}
```

and I make a change anywhere, it resets to 0. Otherwise, it appears to work perfectly -- the page doesn't restart, and network requests aren't made (though I did notice that it requested images again, strangely)

One additional data point that I think is irrelevant: when I tested making a change with `speed-measure-webpack-plugin` enabled, I found that `ReactRefreshPlugin` takes between 2-10 seconds to finish. I assume that's roughly expected, but I figured I'd throw it in there just in case

**Comment by pmmmwh** [comment] 2021-06-09 22:08
Can you create a reproduction? You have a different problem than the OP and is likely due to misconfiguration (e.g. something causing components to not register properly, or `react-refresh/babel` not transforming correctly).

Depending on how big your project and how complex it is, this plugin would take time as we touches all your files basically.

**Comment by pmmmwh** [comment] 2021-06-15 00:38
I'll be closing this issue as the original issue was resolved - feel free to open a new one if there are any new questions/reproductions of issues 😄

**Closed by pmmmwh** 2021-06-15 00:38 UTC
